// scripts/convertData.cjs
const fs = require('fs');
const path = require('path');
const iconv = require('iconv-lite');
const { parse } = require('csv-parse/sync');
const XLSX = require('xlsx');

const DATA_DIR = path.join(__dirname, '../raw_data');
const OUT_FILE = path.join(__dirname, '../src/data/mockData.js');

const findFile = (keyword) => {
  try {
    const files = fs.readdirSync(DATA_DIR);
    return files.find(f => f.includes(keyword) && !f.startsWith('~$'));
  } catch (e) {
    return null;
  }
};

const FILE_MASTER = findFile('FUND_MASTER');
const FILE_PRICE = findFile('FUND_PRICE');
const FILE_INDEX = findFile('指数');

console.log("🚀 데이터 변환 및 복구를 시작합니다...");

const readTsv = (fileName) => {
  if (!fileName) return [];
  const filePath = path.join(DATA_DIR, fileName);
  try {
    const buffer = fs.readFileSync(filePath);
    const decoded = iconv.decode(buffer, 'Shift_JIS');
    return parse(decoded, { delimiter: '\t', columns: true, skip_empty_lines: true, relax_column_count: true });
  } catch (e) {
    return [];
  }
};

const masterData = readTsv(FILE_MASTER);
const priceData = readTsv(FILE_PRICE);

const priceMap = new Map();
priceData.forEach(row => {
  if (!row.QUICKCODE) return;
  priceMap.set(row.QUICKCODE, {
    basePrice: Number(row.PRICE) || 0,
    netAssets: row.NET_ASSET_VALUE || "0",
    prevComparison: Number(row.TOURAKU_1D) || 0,
    prevPercent: Number(row.TOURAKU_1D_PER) || 0
  });
});

const funds = masterData.map((row, index) => {
  const code = row.QUICKCODE;
  const price = priceMap.get(code) || { basePrice: 0, netAssets: "0", prevComparison: 0, prevPercent: 0 };
  return {
    id: index + 1,
    fundCode: row.ISIN_CODE || code,
    shortCode: code,
    fundName: row.FUND_SHORT_NAME || row.OFFICIAL_FUND_NAME || "Unknown",
    category: row.QUICK_CATEGORY || "General",
    riskLevel: 3, 
    basePrice: price.basePrice,
    prevComparison: price.prevComparison,
    prevComparisonPercent: price.prevPercent,
    netAssets: Math.round(Number(price.netAssets)) + " 億円",
    managementCompany: "Unknown",
    trustFee: Number(row.NET_TRUSTFEE) || 0
  };
}).slice(0, 100);

let marketIndices = [
  { name: "日経225", value: 38500, change: 0.5 },
  { name: "S&P 500", value: 5100, change: 0.8 },
  { name: "NASDAQ", value: 16200, change: 1.2 },
  { name: "USD/JPY", value: 148.5, change: -0.2 },
];

if (FILE_INDEX) {
  try {
    const workbook = XLSX.readFile(path.join(DATA_DIR, FILE_INDEX));
    const sheetName = workbook.SheetNames.find(s => s.includes('世界') || s.includes('指数'));
    if (sheetName) {
      const rows = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], { header: 1 });
      const targetIndices = { '日経平均': '日経225', 'S&P500': 'S&P 500', 'NASDAQ総合': 'NASDAQ', 'NYダウ': 'NYダウ', 'TOPIX': 'TOPIX' };
      const foundIndices = [];
      rows.forEach(row => {
        if (targetIndices[row[3]]) {
            foundIndices.push({ name: targetIndices[row[3]], value: Number(row[4]), change: Number(row[6]) });
        }
      });
      if (foundIndices.length > 0) marketIndices = foundIndices;
    }
  } catch (e) {}
}

// ★ 이 부분이 반드시 있어야 에러가 안 납니다!
const initialUsers = [
  { id: 1, name: "山田 太郎", email: "taro@example.com", plan: "premium", status: "active", lastLogin: "2024-03-10" },
  { id: 2, name: "鈴木 花子", email: "hanako@example.com", plan: "free", status: "active", lastLogin: "2024-03-09" },
  { id: 3, name: "佐藤 次郎", email: "jiro@example.com", plan: "free", status: "inactive", lastLogin: "2024-02-28" },
  { id: 4, name: "田中 美咲", email: "misaki@example.com", plan: "premium", status: "active", lastLogin: "2024-03-10" },
  { id: 5, name: "高橋 健一", email: "ken1@example.com", plan: "free", status: "warning", lastLogin: "2024-03-05" },
];

const fileContent = `
// Auto-generated by scripts/convertData.cjs
export const funds = ${JSON.stringify(funds, null, 2)};
export const marketIndices = ${JSON.stringify(marketIndices, null, 2)};
export const INITIAL_USERS = ${JSON.stringify(initialUsers, null, 2)};
`;

fs.writeFileSync(OUT_FILE, fileContent, 'utf-8');
console.log(`✅ 데이터 복구 완료!`);